port: 3001 #puerto de salida
database: "mongodb+srv://Hexzzard:homerochino@cluster0.6iqmxms.mongodb.net/" #conexion a la bd
dbname: "mybd"
key : "Validator me arruino la vida :c " #string de 32 caracteres para cifrado